insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (101, 'Levi''s Jeans', 'Jeans', 13.17, 4.96, 44);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (102, 'Nike shirt', 'Shirt', 19.41, 15.05, 21);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (103, 'Levi''s Jeans', 'Jeans', 14.66, 6.99, 46);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (104, 'Toy Car', 'Toy', 15.01, 17.12, 18);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (105, 'Nike shirt', 'Shirt', 1.36, 22.93, 14);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (106, 'Levi''s Jeans', 'Jeans', 11.46, 5.69, 47);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (107, 'Nike shirt', 'Shirt', 9.93, 7.88, 36);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (108, 'Nike shirt', 'Shirt', 6.41, 13.1, 40);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (109, 'Nike shirt', 'Shirt', 11.72, 17.05, 45);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (110, 'Titan Watch', 'Watch', 1.56, 24.07, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (111, 'Titan Watch', 'Watch', 17.96, 7.81, 19);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (112, 'Titan Watch', 'Watch', 8.44, 13.84, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (113, 'Levi''s Jeans', 'Jeans', 4.15, 17.92, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (114, 'Nike shirt', 'Shirt', 12.29, 16.46, 13);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (115, 'Toy Car', 'Shorts', 3.17, 3.81, 37);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (116, 'Nike shirt', 'Shirt', 12.01, 8.65, 17);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (117, 'Levi''s Jeans', 'Jeans', 1.4, 6.57, 18);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (118, 'Titan Watch', 'Shorts', 16.73, 7.02, 20);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (119, 'Nike shirt', 'Shirt', 4.45, 10.62, 21);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (110, 'Levi''s Jeans', 'Jeans', 14.99, 10.94, 46);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (111, 'Levi''s Jeans', 'Jeans', 17.76, 2.9, 4);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (112, 'Levi''s Jeans', 'Jeans', 12.56, 8.74, 27);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (113, 'Nike T Shirt', 'T Shirt', 18.61, 11.38, 30);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (114, 'Nike T Shirt', 'T Shirt', 18.18, 22.14, 14);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (115, 'Reebok Shoes', 'Shoes', 18.95, 11.48, 15);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (116, 'Nike shirt', 'Shoes', 16.37, 15.2, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (117, 'Reebok Shoes', 'Shoes', 14.48, 3.72, 20);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (118, 'Toy Car', 'Toy', 4.31, 7.97, 20);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (119, 'Reebok Shoes', 'Shoes', 13.9, 13.54, 17);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (120, 'Reebok Shoes', 'Shoes', 12.21, 20.98, 42);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (121, 'Levi''s Jeans', 'Jeans', 2.16, 8.72, 33);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (122, 'Nike shirt', 'Shirt', 3.2, 16.85, 17);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (123, 'Levi''s Jeans', 'Jeans', 7.57, 20.4, 3);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (124, 'Levi''s Jeans', 'Jeans', 19.26, 5.8, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (125, 'Toy Car', 'Jeans', 4.94, 22.65, 6);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (126, 'Levi''s Jeans', 'Jeans', 13.95, 3.44, 15);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (127, 'Toy Car', 'Toy', 4.27, 13.74, 20);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (128, 'Toy Car', 'Toy', 7.31, 13.87, 15);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (129, 'Levi''s Jeans', 'Jeans', 12.82, 8.67, 41);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (130, 'Reebok Shorts', 'Shorts', 14.07, 3.3, 4);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (131, 'Reebok Shoes', 'Shoes', 15.69, 18.1, 41);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (132, 'Reebok Shoes', 'Shoes', 10.23, 7.53, 27);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (133, 'Toy Car', 'Toy', 7.86, 2.96, 26);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (134, 'Toy Car', 'Toy', 7.48, 13.08, 3);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (135, 'Toy Car', 'Toy', 10.18, 8.52, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (136, 'Titan Watch', 'Watch', 3.76, 5.38, 37);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (137, 'Nike T Shirt', 'T Shirt', 5.84, 3.05, 26);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (138, 'Toy Car', 'Toy', 18.9, 9.05, 5);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (139, 'Reebok Shoes', 'Shoes', 3.36, 22.66, 26);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (140, 'Reebok Shoes', 'Shoes', 11.13, 7.43, 22);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (141, 'Nike shirt', 'Shirt', 7.56, 21.33, 10);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (142, 'Reebok Shoes', 'Shoes', 10.29, 17.35, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (143, 'Titan Watch', 'Watch', 5.63, 4.38, 10);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (144, 'Reebok Shoes', 'Shoes', 5.45, 6.11, 38);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (145, 'Titan Watch', 'Watch', 18.7, 14.12, 37);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (146, 'Reebok Shoes', 'Shoes', 4.85, 8.69, 30);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (147, 'Nike shirt', 'Shirt', 19.52, 16.75, 23);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (148, 'Toy Car', 'Toy', 12.76, 12.39, 18);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (149, 'Nike T shirt', 'T shirt', 19.5, 1.55, 20);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (150, 'Nike T shirt', 'T shirt', 12.72, 7.86, 31);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (151, 'Reebok Shoes', 'Shoes', 17.3, 16.68, 41);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (152, 'Reebok Shorts', 'Shorts', 11.6, 5.66, 24);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (153, 'Reebok Shorts', 'Shorts', 3.72, 17.84, 9);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (154, 'Titan Watch', 'Watch', 15.19, 1.26, 27);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (155, 'Toy Car', 'Toy', 2.9, 7.13, 12);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (156, 'Titan Watch', 'Shoes', 5.25, 20.08, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (157, 'Reebok Shoes', 'Shoes', 12.17, 21.92, 35);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (158, 'Titan Watch', 'Watch', 12.9, 13.98, 19);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (159, 'Nike shirt', 'Shirt', 10.88, 13.46, 27);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (160, 'Toy Car', 'Toy', 11.02, 3.78, 10);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (161, 'Nike shirt', 'Shirt', 13.5, 1.02, 48);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (162, 'Titan Watch', 'Watch', 5.33, 3.27, 3);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (163, 'Nike T shirt', 'T Shirt', 8.93, 17.65, 50);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (164, 'Titan Watch', 'Watch', 2.95, 2.7, 27);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (165, 'Titan Watch', 'Watch', 10.6, 6.75, 50);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (166, 'Reebok Shoes', 'Shoes', 1.15, 24.12, 30);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (167, 'Nike T shirt', 'T shirt', 19.99, 15.51, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (168, 'Nike T shirt', 'T shirt', 2.01, 11.64, 30);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (169, 'Toy Car', 'Toy', 10.28, 19.79, 11);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (170, 'Levi''s Jeans', 'Jeans', 11.76, 18.87, 31);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (171, 'Reebok Shoes', 'Shoes', 4.62, 5.95, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (172, 'Nike T shirt', 'T Shirt', 12.49, 23.06, 39);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (173, 'Nike T shirt', 'T Shirt', 5.98, 22.27, 41);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (174, 'Reebok Shoes', 'Shoes', 16.76, 21.39, 18);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (175, 'Toy Car', 'Toy', 1.04, 10.3, 36);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (176, 'Reebok Shoes', 'Shoes', 12.97, 7.97, 26);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (177, 'Reebok Shoes', 'Shoes', 17.1, 22.86, 12);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (178, 'Titan Watch', 'Watch', 3.17, 17.34, 7);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (179, 'Titan Watch', 'Watch', 12.27, 8.49, 37);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (180, 'Reebok Shoes', 'Shoes', 5.14, 20.97, 41);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (181, 'Titan Watch', 'Watch', 5.68, 12.24, 50);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (182, 'Toy Car', 'Toy', 8.11, 16.67, 49);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (183, 'Titan Watch', 'Watch', 18.05, 1.24, 31);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (184, 'Toy Car', 'Toy', 19.43, 12.25, 2);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (185, 'Levi''s Jeans', 'Jeans', 10.05, 16.02, 26);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (186, 'Nike shirt', 'Shirt', 16.21, 9.19, 15);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (187, 'Nike shirt', 'Shirt', 12.92, 7.67, 6);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (188, 'Nike shirt', 'Shirt', 2.06, 10.96, 32);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (189, 'Nike T Shirt', 'T Shirt', 9.12, 21.44, 46);
insert into Product (categoryID, productName, productDescription, purchasePrice, sellingPrice, productQuantityAvail) values (190, 'Toy Car', 'Toy', 7.61, 21.1, 34);
