insert into Reviews (customerID, productID, ratings, comments) values (1440, 400, 4, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1657, 401, 4, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1176, 402, 3, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1820, 403, 3, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1326, 404, 3, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1929, 405, 3, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1636, 406, 2, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1944, 407, 2, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1966, 408, 3, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1544, 409, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1814, 410, 5, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1844, 411, 4, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1539, 412, 3, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1190, 413, 2, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1708, 414, 1, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1152, 415, 5, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1404, 416, 3, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1170, 417, 4, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1389, 418, 2, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1227, 419, 3, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1073, 420, 2, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1879, 421, 5, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1279, 422, 5, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1393, 423, 4, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1797, 424, 2, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1202, 425, 1, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1305, 426, 5, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1842, 427, 5, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1082, 428, 5, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1859, 429, 1, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1749, 430, 2, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1538, 431, 2, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1132, 432, 4, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1405, 433, 1, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1150, 434, 2, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1310, 435, 2, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1424, 436, 4, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1141, 437, 2, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1353, 438, 3, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1629, 439, 3, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1066, 440, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1655, 441, 4, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1663, 442, 2, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1713, 443, 1, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1240, 444, 4, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1453, 445, 1, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1437, 446, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1389, 447, 2, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1297, 448, 3, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1604, 449, 5, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1992, 450, 3, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1222, 451, 3, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1586, 452, 4, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1591, 453, 5, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1733, 454, 2, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1565, 455, 4, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1765, 456, 2, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1036, 457, 5, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1187, 458, 1, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1804, 459, 2, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1484, 460, 5, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1895, 461, 4, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1364, 462, 3, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1440, 463, 2, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1601, 464, 1, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1302, 465, 5, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1955, 466, 5, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1386, 467, 1, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1953, 468, 2, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1075, 469, 4, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1166, 470, 3, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1894, 471, 1, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1861, 472, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1641, 473, 5, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1262, 474, 4, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1294, 475, 3, 'Great');
insert into Reviews (customerID, productID, ratings, comments) values (1059, 476, 4, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1719, 477, 1, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1331, 478, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1366, 479, 2, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1546, 480, 5, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1960, 481, 4, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1314, 482, 1, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1608, 483, 2, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1857, 484, 3, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1281, 485, 5, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1619, 486, 4, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1476, 487, 5, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1694, 488, 3, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1936, 489, 5, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1426, 490, 1, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1757, 491, 2, 'Amazing');
insert into Reviews (customerID, productID, ratings, comments) values (1585, 492, 3, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1881, 493, 5, 'Poor');
insert into Reviews (customerID, productID, ratings, comments) values (1571, 494, 5, 'Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1802, 495, 3, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1578, 496, 1, 'Bad');
insert into Reviews (customerID, productID, ratings, comments) values (1160, 497, 5, 'Good');
insert into Reviews (customerID, productID, ratings, comments) values (1115, 498, 1, 'Not Delivered on time');
insert into Reviews (customerID, productID, ratings, comments) values (1937, 499, 3, 'Not Delivered on time');
