insert into Vendor (vendorName, vendorAddress) values ('Bobbee Phizackarley', '366 Gateway Road');
insert into Vendor (vendorName, vendorAddress) values ('Phedra Perillo', '49302 Anhalt Parkway');
insert into Vendor (vendorName, vendorAddress) values ('Nappie Padbery', '08537 Eastlawn Drive');
insert into Vendor (vendorName, vendorAddress) values ('Brant Quinnell', '077 Johnson Terrace');
insert into Vendor (vendorName, vendorAddress) values ('Irving Keinrat', '29924 Fieldstone Avenue');
insert into Vendor (vendorName, vendorAddress) values ('Weylin Barthrup', '82740 Victoria Circle');
insert into Vendor (vendorName, vendorAddress) values ('Heriberto Stobbe', '75 Vidon Pass');
insert into Vendor (vendorName, vendorAddress) values ('Natala Kingdom', '96965 Manitowish Road');
insert into Vendor (vendorName, vendorAddress) values ('Benjy Francescuccio', '9 Springs Pass');
insert into Vendor (vendorName, vendorAddress) values ('Bobbee Phizackarley', '85478 Victoria Way');
insert into Vendor (vendorName, vendorAddress) values ('Bobbee Phizackarley', '05 Dryden Hill');
insert into Vendor (vendorName, vendorAddress) values ('Brigitta Eastcourt', '3210 Sherman Hill');
insert into Vendor (vendorName, vendorAddress) values ('Heriberto Stobbe', '02 Marcy Lane');
insert into Vendor (vendorName, vendorAddress) values ('Doris Tilley', '65268 Old Shore Court');
insert into Vendor (vendorName, vendorAddress) values ('Calida Raden', '1 Randy Alley');
insert into Vendor (vendorName, vendorAddress) values ('Jocelyn Zanicchelli', '90641 Sunbrook Avenue');
insert into Vendor (vendorName, vendorAddress) values ('Meta Skey', '431 Carey Lane');
insert into Vendor (vendorName, vendorAddress) values ('Nappie Padbery', '82409 Paget Way');
insert into Vendor (vendorName, vendorAddress) values ('Georgette Murrock', '8861 Everett Street');
insert into Vendor (vendorName, vendorAddress) values ('Benjy Francescuccio', '2363 Arizona Circle');
insert into Vendor (vendorName, vendorAddress) values ('Natala Kingdom', '937 Loeprich Place');
insert into Vendor (vendorName, vendorAddress) values ('Tillie Wallas', '45657 Sutherland Plaza');
insert into Vendor (vendorName, vendorAddress) values ('Amargo Reach', '1052 Tennessee Pass');
insert into Vendor (vendorName, vendorAddress) values ('Hedwig Lowle', '73 Larry Place');
insert into Vendor (vendorName, vendorAddress) values ('Mile Havock', '87 Talmadge Crossing');
insert into Vendor (vendorName, vendorAddress) values ('Meta Skey', '88 Spohn Plaza');
insert into Vendor (vendorName, vendorAddress) values ('Tessa Vant', '68868 Westport Lane');
insert into Vendor (vendorName, vendorAddress) values ('Shandeigh Foldes', '13 Sloan Park');
insert into Vendor (vendorName, vendorAddress) values ('Karmen Mowle', '446 Manitowish Place');
insert into Vendor (vendorName, vendorAddress) values ('Georgette Murrock', '99398 Kings Junction');
insert into Vendor (vendorName, vendorAddress) values ('Georgette Murrock', '990 Sundown Hill');
insert into Vendor (vendorName, vendorAddress) values ('Urson Swetland', '522 Summit Avenue');
insert into Vendor (vendorName, vendorAddress) values ('Lydia Kinset', '3749 Lyons Pass');
insert into Vendor (vendorName, vendorAddress) values ('Brant Quinnell', '02 Debs Way');
insert into Vendor (vendorName, vendorAddress) values ('Ellary Betham', '7877 Redwing Place');
insert into Vendor (vendorName, vendorAddress) values ('Ellary Betham', '77081 Stuart Hill');
insert into Vendor (vendorName, vendorAddress) values ('Georgette Murrock', '8 Express Drive');
insert into Vendor (vendorName, vendorAddress) values ('Hayes Hendricks', '4 Myrtle Pass');
insert into Vendor (vendorName, vendorAddress) values ('Heriberto Stobbe', '77983 West Center');
insert into Vendor (vendorName, vendorAddress) values ('Mile Havock', '7287 Waywood Place');
insert into Vendor (vendorName, vendorAddress) values ('Irving Keinrat', '5 Messerschmidt Court');
insert into Vendor (vendorName, vendorAddress) values ('Meridel Hooban', '659 Schiller Crossing');
insert into Vendor (vendorName, vendorAddress) values ('Harman McTear', '8640 Heath Crossing');
insert into Vendor (vendorName, vendorAddress) values ('Mordecai Malster', '34846 Pond Pass');
insert into Vendor (vendorName, vendorAddress) values ('Thorin Murden', '895 Maple Wood Hill');
insert into Vendor (vendorName, vendorAddress) values ('Aidan Drogan', '962 Ilene Plaza');
insert into Vendor (vendorName, vendorAddress) values ('Weylin Barthrup', '4 Heath Plaza');
insert into Vendor (vendorName, vendorAddress) values ('Hayes Hendricks', '62 Brentwood Crossing');
insert into Vendor (vendorName, vendorAddress) values ('Kendricks Duplain', '40 Oriole Street');
insert into Vendor (vendorName, vendorAddress) values ('Harriette Beddon', '630 Ronald Regan Park');
insert into Vendor (vendorName, vendorAddress) values ('Odille Maffione', '1 Old Shore Avenue');
insert into Vendor (vendorName, vendorAddress) values ('Abbe O''''Geaney', '200 Di Loreto Street');
insert into Vendor (vendorName, vendorAddress) values ('Lusa Haymes', '61591 Garrison Pass');
insert into Vendor (vendorName, vendorAddress) values ('Bobbee Phizackarley', '2 Nevada Pass');
insert into Vendor (vendorName, vendorAddress) values ('Brigit Filkin', '6625 Ryan Point');
insert into Vendor (vendorName, vendorAddress) values ('Marysa Frears', '572 Mitchell Terrace');
insert into Vendor (vendorName, vendorAddress) values ('Harriette Beddon', '06 Heffernan Park');
insert into Vendor (vendorName, vendorAddress) values ('Homere Peagram', '61184 5th Junction');
insert into Vendor (vendorName, vendorAddress) values ('Meta Skey', '4814 Fremont Place');
insert into Vendor (vendorName, vendorAddress) values ('Odille Maffione', '2602 Jana Place');
insert into Vendor (vendorName, vendorAddress) values ('Gaston Chitter', '352 Meadow Valley Crossing');
insert into Vendor (vendorName, vendorAddress) values ('Bobbee Phizackarley', '76 Bashford Drive');
insert into Vendor (vendorName, vendorAddress) values ('Clare Feare', '27142 Namekagon Park');
insert into Vendor (vendorName, vendorAddress) values ('Meta Skey', '18 Spohn Way');
insert into Vendor (vendorName, vendorAddress) values ('Karmen Mowle', '36 Trailsway Road');
insert into Vendor (vendorName, vendorAddress) values ('Corabel Konrad', '11153 Vernon Terrace');
insert into Vendor (vendorName, vendorAddress) values ('Guglielma Mundie', '2783 Chive Circle');
insert into Vendor (vendorName, vendorAddress) values ('Gaston Chitter', '80 Vera Lane');
insert into Vendor (vendorName, vendorAddress) values ('Kendricks Duplain', '5496 Dunning Way');
insert into Vendor (vendorName, vendorAddress) values ('Dwain Wemm', '7664 Oneill Junction');
insert into Vendor (vendorName, vendorAddress) values ('Franni Streater', '9 Hoepker Street');
insert into Vendor (vendorName, vendorAddress) values ('Brigit Filkin', '61576 Hauk Way');
insert into Vendor (vendorName, vendorAddress) values ('Brant Quinnell', '17 Elka Drive');
insert into Vendor (vendorName, vendorAddress) values ('Hedwig Lowle', '63 Amoth Alley');
insert into Vendor (vendorName, vendorAddress) values ('Marysa Frears', '0 Hollow Ridge Court');
insert into Vendor (vendorName, vendorAddress) values ('Deloris Hartfield', '465 Di Loreto Park');
insert into Vendor (vendorName, vendorAddress) values ('Brigit Filkin', '0 Stone Corner Trail');
insert into Vendor (vendorName, vendorAddress) values ('Tilly Beynkn', '61 Mcbride Road');
insert into Vendor (vendorName, vendorAddress) values ('Clare Feare', '64 Brentwood Street');
insert into Vendor (vendorName, vendorAddress) values ('Tessa Vant', '1 Quincy Trail');
insert into Vendor (vendorName, vendorAddress) values ('Zita Guillain', '8653 Shoshone Trail');
insert into Vendor (vendorName, vendorAddress) values ('Ruthann Khomin', '2 Bartelt Lane');
insert into Vendor (vendorName, vendorAddress) values ('Alison Warby', '351 Florence Road');
insert into Vendor (vendorName, vendorAddress) values ('Irving Keinrat', '3 Mandrake Hill');
insert into Vendor (vendorName, vendorAddress) values ('Aidan Drogan', '10265 Forest Center');
insert into Vendor (vendorName, vendorAddress) values ('Heriberto Stobbe', '61 Eliot Street');
insert into Vendor (vendorName, vendorAddress) values ('Odille Maffione', '718 Butterfield Avenue');
insert into Vendor (vendorName, vendorAddress) values ('Clarita Astell', '237 Shasta Park');
insert into Vendor (vendorName, vendorAddress) values ('Rowena Bilney', '80606 Dakota Alley');
insert into Vendor (vendorName, vendorAddress) values ('Clarita Astell', '9390 Jana Lane');
insert into Vendor (vendorName, vendorAddress) values ('Weylin Barthrup', '25703 Bellgrove Court');
insert into Vendor (vendorName, vendorAddress) values ('Brigitta Eastcourt', '92 Londonderry Terrace');
insert into Vendor (vendorName, vendorAddress) values ('Casper Tittletross', '23158 Briar Crest Drive');
insert into Vendor (vendorName, vendorAddress) values ('Marysa Frears', '860 Sullivan Center');
insert into Vendor (vendorName, vendorAddress) values ('Nappie Padbery', '626 Fulton Trail');
insert into Vendor (vendorName, vendorAddress) values ('Sayre Allsebrook', '0 Oriole Junction');
insert into Vendor (vendorName, vendorAddress) values ('Ellary Betham', '7 Dovetail Hill');
insert into Vendor (vendorName, vendorAddress) values ('Kendricks Duplain', '32 Maywood Plaza');
insert into Vendor (vendorName, vendorAddress) values ('Brigitta Eastcourt', '53 Summer Ridge Road');
insert into Vendor (vendorName, vendorAddress) values ('Rowena Bilney', '5214 Stone Corner Road');
